//      -----------------------------------------------------------------------
//      Licensed Materials - Property of IBM
//      IBM WebSphere ILOG JRules
//      (c) Copyright IBM Corporation 1987, 2010. All Rights Reserved.
//      RuleApp: RuleApp
//      Date: Fri, 17 Jan 2014 11:47:44 CET
//      Generated by: ILOG JRules 7.1.1.5
//
//      N O T I C E
//
//      Changes to this file will be lost if the code is regenerated.
//      Note to U.S. Government Users Restricted Rights: 
//      Use, duplication or disclosure restricted by GSA ADP Schedule 
//      Contract with IBM Corp.
//     -----------------------------------------------------------------------

package RuleApp;

import ilog.rules.res.session.IlrSessionRequest;
import ilog.rules.res.session.IlrSessionResponse;

public class ExecutionHook {
	public IlrSessionResponse postProcessing(IlrSessionRequest request,
			IlrSessionResponse response) {
		// TODO add your code here
		return response;
	}

	public IlrSessionRequest preProcessing(IlrSessionRequest request) {
		// TODO add your code here
		return request;
	}
}
