//      -----------------------------------------------------------------------
//      Licensed Materials - Property of IBM
//      IBM WebSphere ILOG JRules
//      (c) Copyright IBM Corporation 1987, 2010. All Rights Reserved.
//      RuleApp: RuleApp
//      Date: Fri, 17 Jan 2014 11:47:44 CET
//      Generated by: ILOG JRules 7.1.1.5
//
//      N O T I C E
//
//      Changes to this file will be lost if the code is regenerated.
//      Note to U.S. Government Users Restricted Rights: 
//      Use, duplication or disclosure restricted by GSA ADP Schedule 
//      Contract with IBM Corp.
//     -----------------------------------------------------------------------

package RuleApp;

import com.ibm.support.PMR.Portfolio;

public class RulesRequest {

	protected String executionId;

	// in and inout ruleset parameters
	protected Portfolio myMainportfolio;

	protected Portfolio mySecondaryportfolio;

	protected short counter;

	/**
	 * @return Returns the myMainportfolio.
	 */
	public Portfolio getMyMainportfolio() {
		return myMainportfolio;
	}

	/**
	 * @param myMainportfolio
	 *            The myMainportfolio to set.
	 */
	public void setMyMainportfolio(Portfolio myMainportfolio) {
		this.myMainportfolio = myMainportfolio;
	}

	/**
	 * @return Returns the mySecondaryportfolio.
	 */
	public Portfolio getMySecondaryportfolio() {
		return mySecondaryportfolio;
	}

	/**
	 * @param mySecondaryportfolio
	 *            The mySecondaryportfolio to set.
	 */
	public void setMySecondaryportfolio(Portfolio mySecondaryportfolio) {
		this.mySecondaryportfolio = mySecondaryportfolio;
	}

	/**
	 * @return Returns the counter.
	 */
	public short getCounter() {
		return counter;
	}

	/**
	 * @param counter
	 *            The counter to set.
	 */
	public void setCounter(short counter) {
		this.counter = counter;
	}

	/**
	 * @return Returns the executionId.
	 */
	public String getExecutionId() {
		return executionId;
	}

	/**
	 * @param executionId
	 *            The executionId to set.
	 */
	public void setExecutionId(String executionId) {
		this.executionId = executionId;
	}

	public String toString() {
		return super.toString() + "[" + "," + getMyMainportfolio().toString()
				+ "," + getMySecondaryportfolio().toString() + ","
				+ getCounter() + "]";
	}
}
