//      -----------------------------------------------------------------------
//      Licensed Materials - Property of IBM
//      IBM WebSphere ILOG JRules
//      (c) Copyright IBM Corporation 1987, 2010. All Rights Reserved.
//      RuleApp: RuleApp
//      Date: Fri, 17 Jan 2014 11:47:44 CET
//      Generated by: ILOG JRules 7.1.1.5
//
//      N O T I C E
//
//      Changes to this file will be lost if the code is regenerated.
//      Note to U.S. Government Users Restricted Rights: 
//      Use, duplication or disclosure restricted by GSA ADP Schedule 
//      Contract with IBM Corp.
//     -----------------------------------------------------------------------

package RuleApp;

import com.ibm.support.PMR.Store;
import com.ibm.support.PMR.Portfolio;

public class RulesResult {
	// inout and out ruleset parameters
	protected Portfolio myMainportfolio;

	protected Portfolio mySecondaryportfolio;

	protected Store Store;

	protected long Exectime;

	// User data set before the execution
	protected String userdata;

	// Context.out
	protected String outputString;

	protected String executionId;

	/**
	 * @return Returns the myMainportfolio.
	 */
	public Portfolio getMyMainportfolio() {
		return myMainportfolio;
	}

	/**
	 * @param myMainportfolio
	 *            The myMainportfolio to set.
	 */
	public void setMyMainportfolio(Portfolio myMainportfolio) {
		this.myMainportfolio = myMainportfolio;
	}

	/**
	 * @return Returns the mySecondaryportfolio.
	 */
	public Portfolio getMySecondaryportfolio() {
		return mySecondaryportfolio;
	}

	/**
	 * @param mySecondaryportfolio
	 *            The mySecondaryportfolio to set.
	 */
	public void setMySecondaryportfolio(Portfolio mySecondaryportfolio) {
		this.mySecondaryportfolio = mySecondaryportfolio;
	}

	/**
	 * @return Returns the Store.
	 */
	public Store getStore() {
		return Store;
	}

	/**
	 * @param Store
	 *            The Store to set.
	 */
	public void setStore(Store Store) {
		this.Store = Store;
	}

	/**
	 * @return Returns the Exectime.
	 */
	public long getExectime() {
		return Exectime;
	}

	/**
	 * @param Exectime
	 *            The Exectime to set.
	 */
	public void setExectime(long Exectime) {
		this.Exectime = Exectime;
	}

	/**
	 * @return Returns the userdata.
	 */
	public String getUserdata() {
		return userdata;
	}

	/**
	 * @param userdata
	 *            The userdata to set.
	 */
	public void setUserdata(String userdata) {
		this.userdata = userdata;
	}

	/**
	 * @return Returns the outputString.
	 */
	public String getOutputString() {
		return outputString;
	}

	/**
	 * @param outputString
	 *            The outputString to set.
	 */
	public void setOutputString(String outputString) {
		this.outputString = outputString;
	}

	/**
	 * @return Returns the executionId.
	 */
	public String getExecutionId() {
		return executionId;
	}

	/**
	 * @param executionId
	 *            The executionId to set.
	 */
	public void setExecutionId(String executionId) {
		this.executionId = executionId;
	}

	public String toString() {
		return super.toString() + "[" + "," + getMyMainportfolio().toString()
				+ "," + getMySecondaryportfolio().toString() + ","
				+ getStore().toString() + "," + getExectime() + ","
				+ getUserdata() + "," + getOutputString() + "]";
	}
}
