//      -----------------------------------------------------------------------
//      Licensed Materials - Property of IBM
//      IBM WebSphere ILOG JRules
//      (c) Copyright IBM Corporation 1987, 2010. All Rights Reserved.
//      RuleApp: RuleApp
//      Date: Fri, 17 Jan 2014 11:47:44 CET
//      Generated by: ILOG JRules 7.1.1.5
//
//      N O T I C E
//
//      Changes to this file will be lost if the code is regenerated.
//      Note to U.S. Government Users Restricted Rights: 
//      Use, duplication or disclosure restricted by GSA ADP Schedule 
//      Contract with IBM Corp.
//     -----------------------------------------------------------------------

package RuleApp;

import ilog.rules.res.decisionservice.mbean.IlrDecisionServiceMBean;
import ilog.rules.res.decisionservice.mbean.IlrDecisionServiceMBeanException;
import ilog.rules.res.decisionservice.mbean.IlrDecisionServiceMBeanManager;
import ilog.rules.tools.IlrVersionFullInfo;

import java.text.DateFormat;
import java.util.Date;
import java.util.Enumeration;
import java.util.Properties;

import javax.servlet.ServletContext;
import javax.servlet.ServletContextEvent;
import javax.servlet.ServletContextListener;

public class RulesListener implements ServletContextListener {
	public static IlrDecisionServiceMBeanManager MBEAN_MANAGER;

	public void contextInitialized(ServletContextEvent event) {
		Properties jmxprops = getContextParams(event);
		MBEAN_MANAGER = new IlrDecisionServiceMBeanManager(jmxprops);
		register();
	}

	private static void register() {
		Properties props = new Properties();
		props.put(IlrDecisionServiceMBean.KEY_CREATION_DATE, DateFormat
				.getDateInstance(DateFormat.LONG).format(new Date()));
		props.put(IlrDecisionServiceMBean.KEY_AUTHOR, "sp19075");
		props.put(IlrDecisionServiceMBean.KEY_DESCRIPTION, "");
		props.put(IlrDecisionServiceMBean.KEY_VERSION, IlrVersionFullInfo
				.getVersion());
		props.put("wsdlurl", "http://localhost:8080/jaxws-RuleApp/leanWS?wsdl");

		try {
			MBEAN_MANAGER.register("RuleAppRulesDecisionService",
					"/RuleApp/Rules", props);
		} catch (IlrDecisionServiceMBeanException e) {
			System.err.println("DS MBean registration error:");
			e.printStackTrace();
		}
	}

	public void contextDestroyed(ServletContextEvent event) {
		try {
			MBEAN_MANAGER.unregister();
		} catch (IlrDecisionServiceMBeanException e) {
			System.err.println("DS MBean unregistration error:");
			e.printStackTrace();
		}
	}

	private Properties getContextParams(ServletContextEvent event) {
		Properties props = new Properties();

		ServletContext servletContext = event.getServletContext();
		Enumeration e = servletContext.getInitParameterNames();
		while (e.hasMoreElements()) {
			String name = (String) e.nextElement();
			props.setProperty(name, servletContext.getInitParameter(name));
		}

		return props;
	}

	public static IlrDecisionServiceMBeanManager getMBeanManager() {
		return MBEAN_MANAGER;
	}

	public static IlrDecisionServiceMBean getMBean() {
		if (MBEAN_MANAGER.getObjectName() == null)
			register();
		return MBEAN_MANAGER.getMBean();
	}
}
