//      -----------------------------------------------------------------------
//      Licensed Materials - Property of IBM
//      IBM WebSphere ILOG JRules
//      (c) Copyright IBM Corporation 1987, 2010. All Rights Reserved.
//      RuleApp: RuleApp
//      Date: Fri, 17 Jan 2014 11:47:44 CET
//      Generated by: ILOG JRules 7.1.1.5
//
//      N O T I C E
//
//      Changes to this file will be lost if the code is regenerated.
//      Note to U.S. Government Users Restricted Rights: 
//      Use, duplication or disclosure restricted by GSA ADP Schedule 
//      Contract with IBM Corp.
//     -----------------------------------------------------------------------

package RuleApp;

public class RulesetExecutionException extends Exception {
	private static final long serialVersionUID = 1L;
	private String rulesetName;

	public RulesetExecutionException(String rulesetName) {
		this(rulesetName, "");
	}

	public RulesetExecutionException(String rulesetName, String message) {
		super(rulesetName + message);
		this.rulesetName = rulesetName;
	}

	public RulesetExecutionException(String rulesetName, String message,
			Throwable cause) {
		this(rulesetName, message + cause.getMessage());
	}

	public RulesetExecutionException(String rulesetName, Throwable cause) {
		this(rulesetName, cause.getMessage());
	}

	public String getRulesetName() {
		return rulesetName;
	}
}
