
package RuleApp.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1.1
 * 
 */
@XmlRootElement(name = "RulesetExecutionException", namespace = "http://RuleApp")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RulesetExecutionException", namespace = "http://RuleApp", propOrder = {
    "message",
    "rulesetName"
})
public class RulesetExecutionExceptionBean {

    private String message;
    private String rulesetName;

    /**
     * 
     * @return
     *     returns String
     */
    public String getMessage() {
        return this.message;
    }

    /**
     * 
     * @param message
     *     the value for the message property
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * 
     * @return
     *     returns String
     */
    public String getRulesetName() {
        return this.rulesetName;
    }

    /**
     * 
     * @param rulesetName
     *     the value for the rulesetName property
     */
    public void setRulesetName(String rulesetName) {
        this.rulesetName = rulesetName;
    }

}
