//      -----------------------------------------------------------------------
//      Licensed Materials - Property of IBM
//      IBM WebSphere ILOG JRules
//      (c) Copyright IBM Corporation 1987, 2010. All Rights Reserved.
//      RuleApp: RuleApp
//      Date: Fri, 17 Jan 2014 11:47:49 CET
//      Generated by: ILOG JRules 7.1.1.5
//
//      N O T I C E
//
//      Changes to this file will be lost if the code is regenerated.
//      Note to U.S. Government Users Restricted Rights: 
//      Use, duplication or disclosure restricted by GSA ADP Schedule 
//      Contract with IBM Corp.
//     -----------------------------------------------------------------------

package RuleApp;

import java.util.List;

import javax.xml.ws.Holder;

public class LeanWSRunnerClient {

	public static void Rules() {
		LeanWSRunner port = new LeanWSRunnerImplService()
				.getLeanWSRunnerImplPort();

		short counter = 50; // TODO set the initial value
		String executionId = null; // TODO set the initial value
		Holder<String> hexecutionId = new Holder<String>(executionId);
		Portfolio myMainportfolio = null; // TODO set the initial value
		Holder<Portfolio> hmyMainportfolio = new Holder<Portfolio>(
				myMainportfolio);
		Portfolio mySecondaryportfolio = null; // TODO set the initial value
		Holder<Portfolio> hmySecondaryportfolio = new Holder<Portfolio>(
				mySecondaryportfolio);
		Long Exectime = null;
		Holder<Long> hExectime = new Holder<Long>(Exectime);
		Store Store = null;
		Holder<Store> hStore = new Holder<Store>(Store);
		String outputString = null;
		Holder<String> houtputString = new Holder<String>(outputString);
		String userdata = null;
		Holder<String> huserdata = new Holder<String>(userdata);
		huserdata = new Holder<String>(
				"RuleApp.LeanWSRunnerClient.executerules");
		try {
			port.rules(counter, hexecutionId, hmyMainportfolio,
					hmySecondaryportfolio, hExectime,  houtputString,hStore,
					huserdata);
		} catch (RulesetExecutionException_Exception e) {
			e.printStackTrace();
		}
		System.out.println("done");

	}

	public static void main(String[] args) {
		Rules();
	}
}
